---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "One-way repeated measures ANOVA (RB-p design)"
categories: [Univariate, ANOVA]
rerCat: Univariate
tags: [ANOVA]
---

One-way repeated measures ANOVA (RB-p design)
=========================

TODO
-------------------------

 - link to anovaMixed, dfReshape

Traditional univariate analysis and multivariate approach.

Install required packages
-------------------------

[`car`](http://cran.r-project.org/package=car), [`ICSNP`](http://cran.r-project.org/package=ICSNP)

```{r}
wants <- c("car", "ICSNP")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Traditional univariate approach
-------------------------

### Using `aov()` with data in long format

```{r}
set.seed(123)
N      <- 10
P      <- 4
muJ    <- rep(c(-1, 0, 1, 2), each=N)
dfRBpL <- data.frame(id=factor(rep(1:N, times=P)),
                     IV=factor(rep(1:P,  each=N)),
                     DV=rnorm(N*P, muJ, 3))
```

```{r}
summary(aov(DV ~ IV + Error(id/IV), data=dfRBpL))
```

### Effect size estimate: generalized \(\hat{\eta}_{g}^{2}\)

```{r}
(anRes <- anova(lm(DV ~ IV*id, data=dfRBpL)))
```

```{r}
SSEtot <- anRes["id", "Sum Sq"] + anRes["IV:id", "Sum Sq"]
SSb    <- anRes["IV", "Sum Sq"]
```

```{r}
(gEtaSq <- SSb / (SSb + SSEtot))
```

Or from function `ezANOVA()` from package [`ez`](http://cran.r-project.org/package=ez)

### Using `Anova()` from package `car` with data in wide format

```{r}
dfRBpW <- reshape(dfRBpL, v.names="DV", timevar="IV", idvar="id",
                  direction="wide")
```

```{r}
library(car)
fitRBp   <- lm(cbind(DV.1, DV.2, DV.3, DV.4) ~ 1, data=dfRBpW)
inRBp    <- data.frame(IV=gl(P, 1))
AnovaRBp <- Anova(fitRBp, idata=inRBp, idesign=~IV)
summary(AnovaRBp, multivariate=FALSE, univariate=TRUE)
```

### Using `anova.mlm()` and `mauchly.test()` with data in wide format

```{r}
anova(fitRBp, M=~IV, X=~1, idata=inRBp, test="Spherical")
```

```{r}
mauchly.test(fitRBp, M=~IV, X=~1, idata=inRBp)
```

Multivariate approach
-------------------------

### Hotelling's \(T^{2}\)-test using `HotellingsT2()` from package `ICSNP`

```{r}
DVw     <- data.matrix(subset(dfRBpW,
                       select=c("DV.1", "DV.2", "DV.3", "DV.4")))
diffMat <- combn(1:P, 2, function(x) { DVw[ , x[1]] - DVw[ , x[2]] } )
DVdiff  <- diffMat[ , 1:(P-1), drop=FALSE]
muH0    <- rep(0, ncol(DVdiff))
```

```{r}
library(ICSNP)
HotellingsT2(DVdiff, mu=muH0)
```

### Using `Anova()` from package `car`

```{r}
library(car)
summary(AnovaRBp, multivariate=TRUE, univariate=FALSE)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:car))
try(detach(package:nnet))
try(detach(package:MASS))
try(detach(package:ICSNP))
try(detach(package:ICS))
try(detach(package:survey))
try(detach(package:mvtnorm))
```
