---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "One-way ANOVA (CR-p design)"
categories: [Univariate, ANOVA]
rerCat: Univariate
tags: [ANOVA]
---

One-way ANOVA (CR-p design)
=========================

TODO
-------------------------

 - link to normality, varianceHom, regressionDiag, regression for model comparison, resamplingPerm, resamplingBootALM

Install required packages
-------------------------

[`car`](https://cran.r-project.org/package=car), [`DescTools`](https://cran.r-project.org/package=DescTools), [`multcomp`](https://cran.r-project.org/package=multcomp)

```{r}
wants <- c("car", "DescTools", "multcomp")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

CR-\(p\) ANOVA
-------------------------

### Simulate data

```{r}
set.seed(123)
P     <- 4
Nj    <- c(41, 37, 42, 40)
muJ   <- rep(c(-1, 0, 1, 2), Nj)
dfCRp <- data.frame(IV=factor(rep(LETTERS[1:P], Nj)),
                    DV=rnorm(sum(Nj), muJ, 5))
```

```{r rerAnovaCRp01}
plot.design(DV ~ IV, fun=mean, data=dfCRp, main="Group means")
```

### Using `oneway.test()`

#### Assuming variance homogeneity

```{r}
oneway.test(DV ~ IV, data=dfCRp, var.equal=TRUE)
```

#### Generalized Welch-test without assumption of variance homogeneity

```{r}
oneway.test(DV ~ IV, data=dfCRp, var.equal=FALSE)
```

### Using `aov()`

```{r}
aovCRp <- aov(DV ~ IV, data=dfCRp)
summary(aovCRp)
model.tables(aovCRp, type="means")
```

### Model comparisons using `anova(lm())`

```{r}
(anovaCRp <- anova(lm(DV ~ IV, data=dfCRp)))
```

```{r}
anova(lm(DV ~ 1, data=dfCRp), lm(DV ~ IV, data=dfCRp))
```

```{r}
anovaCRp["Residuals", "Sum Sq"]
```

Effect size estimates
-------------------------

```{r}
dfSSb <- anovaCRp["IV",        "Df"]
SSb   <- anovaCRp["IV",        "Sum Sq"]
MSb   <- anovaCRp["IV",        "Mean Sq"]
SSw   <- anovaCRp["Residuals", "Sum Sq"]
MSw   <- anovaCRp["Residuals", "Mean Sq"]
```

\(\hat{\eta^{2}}\)

```{r}
(etaSq <- SSb / (SSb + SSw))
library(DescTools)                     # for EtaSq()
EtaSq(aovCRp, type=1)
```

\(\hat{\omega^{2}}\), \(\hat{f^{2}}\)

```{r}
(omegaSq <- dfSSb * (MSb-MSw) / (SSb + SSw + MSw))
(f <- sqrt(etaSq / (1-etaSq)))
```

Planned comparisons - a-priori
-------------------------

### General contrasts using `glht()` from package `multcomp`

```{r}
cntrMat <- rbind("A-D"          =c(  1,   0,   0,  -1),
                 "1/3*(A+B+C)-D"=c(1/3, 1/3, 1/3,  -1),
                 "B-C"          =c(  0,   1,  -1,   0))
library(multcomp)                      # for glht()
summary(glht(aovCRp, linfct=mcp(IV=cntrMat), alternative="less"),
        test=adjusted("none"))
```

### Pairwise \(t\)-tests

```{r}
pairwise.t.test(dfCRp$DV, dfCRp$IV, p.adjust.method="bonferroni")
```

Planned comparisons - post-hoc
-------------------------

### Scheffe tests

```{r}
library(DescTools)                  # for ScheffeTest()
ScheffeTest(aovCRp, which="IV", contrasts=t(cntrMat))
```

### Tukey's simultaneous confidence intervals

```{r}
(tHSD <- TukeyHSD(aovCRp))
```

```{r rerAnovaCRp02}
plot(tHSD)
```

Using `glht()` from package `multcomp`

```{r}
library(multcomp)                      # for glht()
tukey <- glht(aovCRp, linfct=mcp(IV="Tukey"))
summary(tukey)
confint(tukey)
```

Assess test assumptions
-------------------------

### Normality

```{r rerAnovaCRp03}
Estud <- rstudent(aovCRp)
qqnorm(Estud, pch=20, cex=2)
qqline(Estud, col="gray60", lwd=2)
```

```{r}
shapiro.test(Estud)
```

### Variance homogeneity

```{r rerAnovaCRp04}
plot(Estud ~ dfCRp$IV, main="Residuals per group")
```

```{r}
library(car)
leveneTest(aovCRp)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:car))
try(detach(package:multcomp))
try(detach(package:survival))
try(detach(package:mvtnorm))
try(detach(package:splines))
try(detach(package:TH.data))
try(detach(package:DescTools))
```
