---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Association tests and measures for ordered categorical variables"
categories: [Descriptive]
rerCat: Descriptive
tags: [Association]
---

Association tests and measures for ordered categorical variables
=========================

TODO
-------------------------

 - link to correlation, association, diagCategorical

Install required packages
-------------------------

[`coin`](http://cran.r-project.org/package=coin), [`mvtnorm`](http://cran.r-project.org/package=mvtnorm), [`polycor`](http://cran.r-project.org/package=polycor), [`pROC`](http://cran.r-project.org/package=pROC), [`rms`](http://cran.r-project.org/package=rms)

```{r}
wants <- c("coin", "mvtnorm", "polycor", "pROC", "rms")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Linear-by-linear association test
-------------------------

```{r}
set.seed(123)
library(mvtnorm)
N     <- 100
Sigma <- matrix(c(4,2,-3, 2,16,-1, -3,-1,9), byrow=TRUE, ncol=3)
mu    <- c(-3, 2, 4)
Xdf   <- data.frame(rmvnorm(n=N, mean=mu, sigma=Sigma))
```

```{r}
lOrd   <- lapply(Xdf, function(x) {
                 cut(x, breaks=quantile(x), include.lowest=TRUE,
                     ordered=TRUE, labels=LETTERS[1:4]) })
dfOrd  <- data.frame(lOrd)
matOrd <- data.matrix(dfOrd)
```

```{r}
cTab <- xtabs(~ X1 + X3, data=dfOrd)
addmargins(cTab)
library(coin)
lbl_test(cTab, distribution=approximate(B=9999))
```

Polychoric and polyserial correlation
-------------------------

### Polychoric correlation

```{r}
library(polycor)
polychor(dfOrd$X1, dfOrd$X2, ML=TRUE)
```

```{r}
polychor(cTab, ML=TRUE)
```

### Polyserial correlation

```{r}
library(polycor)
polyserial(Xdf$X2, dfOrd$X3)
```

### Heterogeneous correlation matrices

```{r}
library(polycor)
Xdf2   <- rmvnorm(n=N, mean=mu, sigma=Sigma)
dfBoth <- cbind(Xdf2, dfOrd)
hetcor(dfBoth, ML=TRUE)
```

Association measures involving categorical and continuous variables
-------------------------

### AUC, Kendall's \(\tau_{a}\), Somers' \(D_{xy}\), Goodman & Kruskal's \(\gamma\)

One continuous variable and one dichotomous variable

```{r}
N   <- 100
x   <- rnorm(N)
y   <- x + rnorm(N, 0, 2)
yDi <- ifelse(y <= median(y), 0, 1)
```

Nagelkerke's pseudo-\(R^{2}\) (R2), area under the ROC-Kurve (C), Somers' \(D_{xy}\) (Dxy), Goodman & Kruskal's \(\gamma\) (Gamma), Kendall's \(\tau\) (Tau-a)

```{r}
library(rms)
lrm(yDi ~ x)$stats
```

### Area under the ROC-curve (AUC)

```{r associationOrder01}
library(pROC)
(rocRes <- roc(yDi ~ x, plot=TRUE, ci=TRUE, main="ROC-curve",
               xlab="specificity (TN / (TN+FP))", ylab="sensitivity (TP / (TP+FN))"))
rocCI <- ci.se(rocRes)
plot(rocCI, type="shape")
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:rms))
try(detach(package:Hmisc))
try(detach(package:grid))
try(detach(package:lattice))
try(detach(package:Formula))
try(detach(package:SparseM))
try(detach(package:pROC))
try(detach(package:polycor))
try(detach(package:sfsmisc))
try(detach(package:coin))
try(detach(package:survival))
try(detach(package:mvtnorm))
try(detach(package:splines))
```
