---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Crossvalidation for linear and generalized linear models"
categories: [Univariate]
rerCat: Univariate
tags: [Regression]
---

Crossvalidation for linear and generalized linear models
=========================

Install required packages
-------------------------

[`boot`](http://cran.r-project.org/package=boot)

```{r}
wants <- c("boot")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

\(k\)-fold crossvalidation
-------------------------

### Simulate data
    
```{r}
set.seed(1.234)
N  <- 100
X1 <- rnorm(N, 175, 7)
X2 <- rnorm(N,  30, 8)
X3 <- abs(rnorm(N, 60, 30))
Y  <- 0.5*X1 - 0.3*X2 - 0.4*X3 + 10 + rnorm(N, 0, 3)
dfRegr <- data.frame(X1, X2, X3, Y)
```

### Crossvalidation

```{r}
glmFit <- glm(Y ~ X1 + X2 + X3, data=dfRegr,
              family=gaussian(link="identity"))
```

```{r}
library(boot)
k    <- 3
kfCV <- cv.glm(data=dfRegr, glmfit=glmFit, K=k)
kfCV$delta
```

Leave-one-out crossvalidation
-------------------------

```{r}
LOOCV <- cv.glm(data=dfRegr, glmfit=glmFit, K=N)
```

CVE = mean(PRESS)

```{r}
LOOCV$delta
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:boot))
```
