---
license: Creative Commons BY-SA
author: "Daniel Wollschlaeger"
title: "Create and analyze data frames"
categories: [DataFrames]
rerCat: Data_Frames
tags: [DataFrames]
---

Create and analyze data frames
=========================

TODO
-------------------------

 - link to dfTransform

 Install required packages
-------------------------

[`car`](https://cran.r-project.org/package=car)

```{r}
wants <- c("car")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Create and analyze data frames
-------------------------

### Create data frames

From existing variables

```{r}
set.seed(123)
N      <- 12
sex    <- factor(sample(c("f", "m"), N, replace=TRUE), levels=c("f", "m"))
group  <- factor(sample(rep(c("CG", "WL", "T"), 4), N, replace=FALSE), levels=c("CG", "WL", "T"))
age    <- sample(18:35, N, replace=TRUE)
IQ     <- round(rnorm(N, mean=100, sd=15))
rating <- round(runif(N, min=0, max=6))
(myDf1 <- data.frame(id=1:N, sex, group, age, IQ, rating))
```

### Analyze the structure of data frames

```{r}
dim(myDf1)
nrow(myDf1)
ncol(myDf1)
summary(myDf1)
str(myDf1)
```

```{r}
head(myDf1)
tail(myDf1)
```

```{r}
library(car)
some(myDf1, n=5)
```

```{r eval=FALSE}
View(myDf1)
# not shown - opens separate window / viewer tab in RStudio
```

### Data types in data frames

```{r}
fac   <- c("CG", "T1", "T2")
DV1   <- c(14, 22, 18)
DV2   <- c("red", "blue", "blue")
## stringsAsFactors=FALSE is the default since R 4.0.0
## before, it was TRUE
myDf2 <- data.frame(fac, DV1, DV2, stringsAsFactors=FALSE)
str(myDf2)
```

```{r}
fac   <- factor(fac)
myDf3 <- data.frame(fac, DV1, DV2, stringsAsFactors=FALSE)
str(myDf3)
```

### Names of cases and variables

```{r}
dimnames(myDf1)
names(myDf1)
rownames(myDf1)
```

Select and change observations
-------------------------

Basic indexing method

```{r}
myDf1[[3]]
myDf1[[3]][2]
myDf1$rating
myDf1$age[4]
myDf1$IQ[10:12] <- c(99, 110, 89)
myDf1[3, 4]
myDf1[4, "group"]
myDf1[2, ]
myDf1[, "age"]
myDf1[, "age", drop=FALSE]
```

See dfTransform for selecting subsets of data more conveniently

Work with variables from a data frame
-------------------------

```{r}
with(myDf1, tapply(IQ, group, FUN=mean))
xtabs(~ sex + group, data=myDf1)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:car))
try(detach(package:carData))
```
