---
license: Creative Commons BY-SA
author: "Daniel Wollschlaeger"
title: "Aggregate data frames - base R"
categories: [DataFrames]
rerCat: Data_Frames
tags: [Aggregate]
---

Aggregate data frames - base R
=========================

Simulate data
-------------------------

```{r}
set.seed(123)
N      <- 12
sex    <- factor(sample(c("f", "m"), N, replace=TRUE), levels=c("f", "m"))
group  <- factor(sample(rep(c("CG", "WL", "T"), 4), N, replace=FALSE), levels=c("CG", "WL", "T"))
age    <- sample(18:35, N, replace=TRUE)
IQ     <- round(rnorm(N, mean=100, sd=15))
rating <- round(runif(N, min=0, max=6))
(myDf1 <- data.frame(id=1:N, sex, group, age, IQ, rating))
```

Apply the same function to different variables in a data frame
-------------------------

```{r}
lapply(myDf1[ , c("age", "IQ", "rating")], mean)
sapply(myDf1[ , c("age", "IQ", "rating")], range)
```

```{r}
(numIdx <- sapply(myDf1, is.numeric))
dataNum <- myDf1[ , numIdx]
head(dataNum)
```

Apply the same function to pairs of variables from two data frames
-------------------------

```{r}
N    <- 100
x1   <- rnorm(N, 10, 10)
y1   <- rnorm(N, 10, 10)
x2   <- x1 + rnorm(N, 5, 4)
y2   <- y1 + rnorm(N, 10, 4)
tDf1 <- data.frame(x1, y1)
tDf2 <- data.frame(x2, y2)
```

```{r}
mapply(t.test, tDf1, tDf2, MoreArgs=list(alternative="less", var.equal=TRUE))
```

Separate descriptive statistics for each group for many variables
-------------------------

### `split()` -> `sapply()`

```{r}
(splitRes <- split(myDf1, myDf1$group))
sapply(splitRes, function(x) mean(x$IQ))
```

Here equivalent to

```{r}
tapply(myDf1$IQ, myDf1$group, FUN=mean)
```

### `aggregate()`

```{r}
numDf <- subset(myDf1, select=c("age", "IQ", "rating"))
aggregate(numDf, list(myDf1$sex, myDf1$group), FUN=mean)
aggregate(cbind(age, IQ, rating) ~ sex + group, FUN=mean, data=myDf1)
aggregate(cbind(age, IQ, rating) ~ 1, FUN=mean, data=myDf1)
```

Calculate different measures by group

```{r}
(groupN   <- as.data.frame(xtabs(~ sex + group, data=myDf1)))
(groupM   <- aggregate(age ~ sex + group, data=myDf1, FUN=mean))
(groupSD  <- aggregate(age ~ sex + group, data=myDf1, FUN=sd))
```

Merge all results into one data frame

```{r}
(groupMSD <- merge(groupM, groupSD, by=c("sex", "group"),
                   suffixes=c(".M", ".SD")))
(groupMSDN <- merge(groupMSD, groupN, by=c("sex", "group")))
```
    
### `by()`

```{r}
by(numDf, list(myDf1$sex, myDf1$group), FUN=function(x) sapply(x, mean))
```
