---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Split and merge data frames"
categories: [DataFrames]
rerCat: Data_Frames
tags: [DataFrames]
---

Split and merge data frames
=========================

Simulate data
-------------------------

```{r}
set.seed(123)
N      <- 12
sex    <- factor(sample(c("f", "m"), N, replace=TRUE), levels=c("f", "m"))
group  <- factor(sample(rep(c("CG", "WL", "T"), 4), N, replace=FALSE), levels=c("CG", "WL", "T"))
age    <- sample(18:35, N, replace=TRUE)
IQ     <- round(rnorm(N, mean=100, sd=15))
rating <- round(runif(N, min=0, max=6))
(myDf1 <- data.frame(id=1:N, sex, group, age, IQ, rating))
```

Combine data frames
-------------------------

Bind rows

```{r}
(dfNew <- data.frame(id=13:15,
                     group=c("CG", "WL", "T"),
                     sex=c("f", "f", "m"),
                     age=c(18, 31, 21),
                     IQ=c(116, 101, 99),
                     rating=c(4, 4, 1)))
dfComb <- rbind(myDf1, dfNew)
dfComb
```

Split a data frame according to group membership
-------------------------

```{r}
(lDf <- split(myDf1, myDf1$group))
split(myDf1, list(myDf1$group, myDf1$sex))
unsplit(lDf, myDf1$group)
```

Merge data frames
-------------------------

[Very good illustration of different join types](https://r4ds.had.co.nz/relational-data.html)

### Left outer join

```{r}
(IDDV <- data.frame(ID=factor(rep(1:3, each=2)),
                    DV=round(rnorm(6, 100, 15))))

(IV <- data.frame(ID=factor(1:3),
                  IV=factor(c("A", "B", "A")),
                  sex=factor(c("f", "f", "m"))))

merge(IDDV, IV)
```

Specify identical variables which have different names in the two data sets.

```{r}
(dfA <- data.frame(ID=1:4,
                   initials=c("AB", "CD", "EF", "GH"),
                   IV1=c("-", "-", "+", "+"),
                   DV1=c(10, 10, 11, 14),
                   stringsAsFactors=FALSE))

(dfB <- data.frame(ID_mod=3:6,
                   initials=c("EF", "GH", "IJ", "KL"),
                   IV2=c("A", "B", "A", "B"),
                   DV2=c(92, 79, 101, 81),
                   stringsAsFactors=FALSE))
```

```{r}
merge(dfA, dfB, all.x=TRUE,
      by.x=c("ID", "initials"),
      by.y=c("ID_mod", "initials"))
```

### Right outer join

```{r}
merge(dfA, dfB, all.y=TRUE,
      by.x=c("ID", "initials"),
      by.y=c("ID_mod", "initials"))
```

### Full outer join

```{r}
merge(dfA, dfB, all.x=TRUE, all.y=TRUE,
      by.x=c("ID", "initials"),
      by.y=c("ID_mod", "initials"))
```

### Inner join

```{r}
merge(dfA, dfB,
      by.x=c("ID", "initials"),
      by.y=c("ID_mod", "initials"))
```
