---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Split and merge data frames - dplyr"
categories: [DataFrames]
rerCat: Data_Frames
tags: [DataFrames]
---

Split and merge data frames - package `dplyr`
=========================

Install required packages
-------------------------

[`dplyr`](https://cran.r-project.org/package=dplyr)

```{r}
wants <- c("dplyr")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Simulate data
-------------------------

```{r}
set.seed(123)
N      <- 12
sex    <- factor(sample(c("f", "m"), N, replace=TRUE), levels=c("f", "m"))
group  <- factor(sample(rep(c("CG", "WL", "T"), 4), N, replace=FALSE), levels=c("CG", "WL", "T"))
age    <- sample(18:35, N, replace=TRUE)
IQ     <- round(rnorm(N, mean=100, sd=15))
rating <- round(runif(N, min=0, max=6))
(myDf1 <- data.frame(id=1:N, sex, group, age, IQ, rating))

(myDf2 <- data.frame(id=21,
                     sex=factor("f", levels=c("f", "m")),
                     age=48,
                     rating=3))
```

Combine data frames
-------------------------

Bind rows - does not require identical order of variables / identical variables

```{r}
library(dplyr)
bind_rows(myDf1, myDf2) %>%
    tail(n=3)
```

Merge data frames
-------------------------

[Very good illustration of different join types](https://r4ds.had.co.nz/relational-data.html)

### Left outer join

```{r}
(IDDV <- data.frame(ID=factor(rep(1:3, each=2)),
                    DV=round(rnorm(6, 100, 15))))

(IV <- data.frame(ID=factor(1:3),
                  IV=factor(c("A", "B", "A")),
                  sex=factor(c("f", "f", "m"))))

IDDV %>%
    left_join(IV, by="ID")
```

Specify identical variables which have different names in the two data sets.

```{r}
(dfA <- data.frame(ID=1:4,
                   initials=c("AB", "CD", "EF", "GH"),
                   IV1=c("-", "-", "+", "+"),
                   DV1=c(10, 10, 11, 14),
                   stringsAsFactors=FALSE))

(dfB <- data.frame(ID_mod=3:6,
                   initials=c("EF", "GH", "IJ", "KL"),
                   IV2=c("A", "B", "A", "B"),
                   DV2=c(92, 79, 101, 81),
                   stringsAsFactors=FALSE))
```

```{r}
dfA %>%
    left_join(dfB, by=c("ID"="ID_mod", "initials"))
```

### Right outer join

```{r}
dfA %>%
    right_join(dfB, by=c("ID"="ID_mod", "initials"))
```

### Full outer join

```{r}
dfA %>%
    full_join(dfB, by=c("ID"="ID_mod", "initials"))
```

### Inner join

```{r}
dfA %>%
    inner_join(dfB, by=c("ID"="ID_mod", "initials"))
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:dplyr))
```
