---
license: Creative Commons BY-SA
author: "Daniel Wollschlaeger"
title: "Color, line type, and point shape in ggplot2 diagrams"
categories: [Diagrams, BasicDiagrams]
rerCat: Diagrams
tags: [Diagrams, ggplot2]
---

Color, line type, and point shape in diagrams with the `ggplot2` package
=========================

Install required packages
-------------------------

[`ggplot2`](https://cran.r-project.org/package=ggplot2), [`ggbeeswarm`](https://cran.r-project.org/package=ggbeeswarm)

```{r}
wants <- c("ggplot2", "ggbeeswarm")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Simulate data
-------------------------

Data needs to be in long format such that color / line type / point shape can be controlled via variables.

```{r}
Njk    <- 50
P      <- 4
Q      <- 2
IQ     <- rnorm(P*Q*Njk, mean=100, sd=15)
height <- rnorm(P*Q*Njk, mean=175, sd=7)
rating <- factor(sample(LETTERS[1:3], Njk*P*Q, replace=TRUE))
sex    <- factor(rep(c("f", "m"), times=P*Njk))
group  <- factor(rep(c("control", "placebo", "treatA", "treatB"), each=Q*Njk))
sgComb <- interaction(sex, group)
mood   <- round(rnorm(P*Q*Njk, mean=c(85, 80, 110, 90, 130, 100, 93, 121)[sgComb], sd=25))
myDf   <- data.frame(sex, group, sgComb, IQ, height, rating, mood)
```

Color
-------------------------

### Point / line color

```{r  ggplot_aes01}
library(ggplot2)
ggplot(myDf, aes(x=height, y=IQ, colour=sex)) +
        geom_point(size=3)
```

```{r  ggplot_aes03}
ggplot(myDf, aes(x=height, y=IQ, colour=sex:group)) +
        geom_hline(aes(yintercept=100), linetype=2) +
        geom_vline(aes(xintercept=180), linetype=2) +
        geom_point(size=3) +
        geom_smooth(method=lm, se=TRUE, size=1.2, fullrange=TRUE) +
        facet_grid(sex ~ group) +
        ggtitle("IQ ~ height split by sex and group") +
        theme(legend.position="none") +
        geom_text(aes(x=190, y=70, label=sgComb)) +
        annotate("text", x=165, y=130, label="annotation")
```

### Fill color

```{r ggplot_aes04}
library(ggbeeswarm)
ggplot(myDf, aes(x=sex, y=height, fill=sex)) +
    geom_boxplot(outlier.shape=NULL) +
    geom_beeswarm(alpha=0.5) +
    ggtitle("Height by sex") +
    theme(legend.position="none")
```

```{r ggplot_aes05}
ggplot(myDf, aes(x=height, fill=sex)) +
        geom_histogram(aes(y=..density..))
```

Point shape
-------------------------

```{r  ggplot_aes06}
ggplot(myDf, aes(x=height, y=IQ, shape=sex)) +
        geom_point(size=3)
```

Line type
-------------------------

```{r ggplot_aes07}
(groupM <- aggregate(mood ~ sex + group, data=myDf, FUN=mean))
ggplot(groupM, aes(x=group, y=mood, linetype=sex, group=sex)) +
    geom_point(size=3) +
    geom_line()
```

Further online resources
-------------------------

See [Cookbook for R: `ggplot2` diagrams](https://r-graphics.org/) for many detailed examples of `ggplot2` diagrams.

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:ggbeeswarm))
try(detach(package:ggplot2))
```
