---
license: Creative Commons BY-SA
author: "Daniel Wollschlaeger"
title: "Descriptive statistics for data in matrices"
categories: [Descriptive]
rerCat: Descriptive
tags: [Matrix, Descriptive]
---

Descriptive statistics for data in matrices
=========================

TODO
-------------------------

 - link to matrix, linearAlgebra

Sums and means
-------------------------

```{r}
age    <- c(19, 19, 31, 19, 24, 17, 43, 28)
weight <- c(95, 76, 94, 76, 76, 68, 81, 65)
height <- c(197, 178, 189, 184, 173, 165, 181, 192)
(mat   <- cbind(age, weight, height))
```

```{r}
sum(mat)
rowSums(mat)
mean(mat)
colMeans(mat)
```

Apply any arithmetic function to rows or columns
-------------------------

```{r}
apply(mat, 2, sum)
apply(mat, 1, max)
apply(mat, 1, range)
apply(mat, 2, mean, trim=0.1)
```

Center and scale a matrix
-------------------------

### Using `scale()`

```{r}
(ctrMat <- scale(mat, center=TRUE, scale=FALSE))
colMeans(ctrMat)
(sclMat <- scale(mat, center=TRUE, scale=TRUE))
apply(sclMat, 2, sd)
```

### Using `sweep()`

```{r}
Mj <- rowMeans(mat)
Mk <- colMeans(mat)
sweep(mat, 1, Mj, "-")
t(scale(t(mat), center=TRUE, scale=FALSE))
sweep(mat, 2, Mk, "-")
```

Covariance and correlation matrices
-------------------------

### Covariance matrix

Corrected

```{r}
cov(mat)
cor(mat)
```

Extract the variances from the diagonal

```{r}
diag(cov(mat))
```

Uncorrected

```{r}
(res <- cov.wt(mat, method="ML"))
res$cov
```

### Robust covariance estimator

```{r}
library(robustbase)
covMcd(mat)
```

### Correlation matrix

```{r}
vec <- rnorm(nrow(mat))
cor(mat, vec)
cor(vec, mat)
```

### Robust correlation matrix

```{r}
library(robustbase)
cov_rob <- covMcd(mat, cor=TRUE)
cov_rob$cor
cov_rob$center
```

Detach (automatically) loaded packages (if possible)
-------------------------
    
```{r}
try(detach(package:robustbase))
```
