---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Arithmetic with matrices"
categories: [RBasics]
rerCat: R_Basics
tags: [Matrix]
---

Arithmetic with matrices
=========================

TODO
-------------------------

 - link to linearAlgebra

Sums and means
-------------------------

```{r}
age    <- c(19, 19, 31, 19, 24)
weight <- c(95, 76, 94, 76, 76)
height <- c(197, 178, 189, 184, 173)
(mat   <- cbind(age, weight, height))
```

```{r}
sum(mat)
rowSums(mat)
mean(mat)
colMeans(mat)
```

Apply any arithmetic function to rows or columns
-------------------------

```{r}
apply(mat, 2, sum)
apply(mat, 1, max)
apply(mat, 1, range)
apply(mat, 2, mean, trim=0.1)
```

Matrix algebra
-------------------------

```{r}
Mj <- rowMeans(mat)
Mk <- colMeans(mat)
sweep(mat, 1, Mj, "-")
t(scale(t(mat), center=TRUE, scale=FALSE))
sweep(mat, 2, Mk, "-")
scale(mat, center=TRUE, scale=FALSE)
```

Covariance and correlation matrices
-------------------------

```{r}
cov(mat)
cor(mat)
cov.wt(mat, method="ML")
diag(cov(mat))
```

```{r}
vec <- rnorm(nrow(mat))
cor(mat, vec)
cor(vec, mat)
```
