---
layout: post
title: "Multivariate multiple regression"
categories: [Multivariate]
rerCat: Multivariate
tags: [Multivariate, Regression]
---

Multivariate multiple regression
=========================

TODO
-------------------------

 - link to regressionDiag, anovaSStypes

Install required packages
-------------------------

[`car`](http://cran.r-project.org/package=car)

```{r}
wants <- c("car")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Model fit
-------------------------
    
```{r}
set.seed(1.234)
N  <- 100
X1 <- rnorm(N, 175, 7)
X2 <- rnorm(N, 30, 8)
X3 <- abs(rnorm(N, 60, 30))
Y1 <- 0.2*X1 - 0.3*X2 - 0.4*X3 + 10 + rnorm(N, 0, 10)
Y2 <- -0.3*X2 + 0.2*X3 + rnorm(N, 10)
Y  <- cbind(Y1, Y2)
dfRegr <- data.frame(X1, X2, X3, Y1, Y2)
```

```{r}
(fit <- lm(cbind(Y1, Y2) ~ X1 + X2 + X3, data=dfRegr))
```

```{r}
coef(lm(Y1 ~ X1 + X2 + X3, data=dfRegr))
coef(lm(Y2 ~ X1 + X2 + X3, data=dfRegr))
```

Coefficient tests and overall model test
-------------------------

### Type I sum of squares

```{r}
summary(manova(fit), test="Hotelling-Lawley")
```

```{r results='hide'}
summary(manova(fit), test="Wilks")
summary(manova(fit), test="Roy")
summary(manova(fit), test="Pillai")
```

No possibility to use `confint()` for multivariate models.

### Type II/III sum of squares

Since no interaction is present in the model, SS type II and III are equivalent here.

```{r}
library(car)                           # for Manova()
Manova(fit, type="II")
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:car))
try(detach(package:nnet))
try(detach(package:MASS))
```
