---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Hotelling's T^2-test"
categories: [Multivariate]
rerCat: Multivariate
tags: [tTests]
---

Hotelling's T^2-test
=========================

Install required packages
-------------------------

[`DescTools`](http://cran.r-project.org/package=DescTools), [`mvtnorm`](http://cran.r-project.org/package=mvtnorm)

```{r}
wants <- c("DescTools", "mvtnorm")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

One-sample Hotelling's \(T^{2}\)-test
-------------------------

### Simulate data

```{r}
set.seed(123)
library(mvtnorm)
Nj    <- c(15, 25)
Sigma <- matrix(c(16,-2, -2,9), byrow=TRUE, ncol=2)
mu1   <- c(-4, 4)
Y1    <- round(rmvnorm(Nj[1], mean=mu1, sigma=Sigma))
```

### Using `HotellingsT2()` from package `DescTools`

```{r}
muH0 <- c(-1, 2)
library(DescTools)
HotellingsT2Test(Y1, mu=muH0)
```

### Using `anova.mlm()`

```{r}
Y1ctr  <- sweep(Y1, 2, muH0, "-")
(anRes <- anova(lm(Y1ctr ~ 1), test="Hotelling-Lawley"))
```

Hotelling's \(T^{2}\)-test for two independent samples
-------------------------

### Using `HotellingsT2()` from package `DescTools`

```{r}
mu2 <- c(3, 3)
Y2  <- round(rmvnorm(Nj[2], mean=mu2, sigma=Sigma))
Y12 <- rbind(Y1, Y2)
IV  <- factor(rep(1:2, Nj))
```

```{r}
library(DescTools)
HotellingsT2Test(Y12 ~ IV)
```

### Using `anova.mlm()` or `manova()`

```{r}
anova(lm(Y12 ~ IV), test="Hotelling-Lawley")
summary(manova(Y12 ~ IV), test="Hotelling-Lawley")
```

Hotelling's \(T^{2}\)-test for two dependent samples
-------------------------

### Simulate data

```{r}
N    <- 20
P    <- 2
muJK <- c(90, 100, 85, 105)
Sig  <- 15
Y1t0 <- rnorm(N, mean=muJK[1], sd=Sig)
Y1t1 <- rnorm(N, mean=muJK[2], sd=Sig)
Y2t0 <- rnorm(N, mean=muJK[3], sd=Sig)
Y2t1 <- rnorm(N, mean=muJK[4], sd=Sig)
Ydf  <- data.frame(id=factor(rep(1:N, times=P)),
                   Y1=c(Y1t0, Y1t1),
                   Y2=c(Y2t0, Y2t1),
                   IV=factor(rep(1:P, each=N), labels=c("t0", "t1")))
```

```{r}
dfDiff <- aggregate(cbind(Y1, Y2) ~ id, data=Ydf, FUN=diff)
DVdiff <- data.matrix(dfDiff[ , -1])
muH0   <- c(0, 0)
```

### Using `HotellingsT2()` from package `DescTools`

```{r}
library(DescTools)
HotellingsT2Test(DVdiff, mu=muH0)
```

### Using `anova.mlm()`

```{r}
anova(lm(DVdiff ~ 1), test="Hotelling-Lawley")
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:DescTools))
try(detach(package:mvtnorm))
```
