---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Bowker-test"
categories: [Nonparametric, ClassicalNonparametric]
rerCat: Nonparametric
tags: [Nonparametric, ClassicalNonparametric]
---

Bowker-test
=========================

Install required packages
-------------------------

[`coin`](http://cran.r-project.org/package=coin)

```{r}
wants <- c("coin")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Bowker test
-------------------------

### Using `mcnemar.test()`

```{r}
categ <- factor(1:3, labels=c("lo", "med", "hi"))
drug  <- rep(categ, c(30, 50, 20))
plac  <- rep(rep(categ, length(categ)), c(14,7,9, 5,26,19, 1,7,12))
cTab  <- table(drug, plac)
addmargins(cTab)
```

`mcnemar.test()` automatically runs the Bowker test for tables with more than 2 rows/columns

```{r}
mcnemar.test(cTab)
```

### Using `symmetry_test()` from package `coin`

```{r}
library(coin)
symmetry_test(cTab, teststat="quad", distribution=approximate(B=9999))
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:coin))
try(detach(package:survival))
try(detach(package:splines))
```
