---
layout: post
title: "McNemar-test"
categories: [Nonparametric, ClassicalNonparametric]
rerCat: Nonparametric
tags: [Nonparametric, ClassicalNonparametric]
---

McNemar-test
=========================

Install required packages
-------------------------

[`coin`](http://cran.r-project.org/package=coin)

```{r}
wants <- c("coin")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

McNemar-test
-------------------------

### Using `mcnemar.test()`

```{r}
set.seed(1.234)
N       <- 20
pre     <- rbinom(N, size=1, prob=0.6)
post    <- rbinom(N, size=1, prob=0.4)
preFac  <- factor(pre,  labels=c("no", "yes"))
postFac <- factor(post, labels=c("no", "yes"))
cTab    <- table(preFac, postFac)
addmargins(cTab)
```

```{r}
mcnemar.test(cTab, correct=FALSE)
```

### Using `symmetry_test()` from package `coin`

```{r}
library(coin)
symmetry_test(cTab, teststat="quad", distribution=approximate(B=9999))
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:coin))
try(detach(package:modeltools))
try(detach(package:survival))
try(detach(package:mvtnorm))
try(detach(package:splines))
try(detach(package:stats4))
```
