---
license: Creative Commons BY-SA
author: "Daniel Wollschlaeger"
title: "Stuart-Maxwell-test for marginal homogeneity"
categories: [Nonparametric, ClassicalNonparametric]
rerCat: Nonparametric
tags: [Nonparametric, ClassicalNonparametric]
---

Stuart-Maxwell-test for marginal homogeneity
=========================

Install required packages
-------------------------

[`coin`](https://cran.r-project.org/package=coin), [`DescTools`](https://cran.r-project.org/package=DescTools)

```{r}
wants <- c("coin", "DescTools")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

MH-test
-------------------------

```{r}
categ <- factor(1:3, labels=c("lo", "med", "hi"))
drug  <- rep(categ, c(30, 50, 20))
plac  <- rep(rep(categ, length(categ)), c(14,7,9, 5,26,19, 1,7,12))
cTab  <- table(drug, plac)
addmargins(cTab)
```

```{r}
library(coin)
mh_test(cTab, distribution=approximate(nresample=9999))
```

Bhapkar-Test
-------------------------

```{r}
library(DescTools)
BhapkarTest(cTab)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:coin))
try(detach(package:survival))
try(detach(package:DescTools))
```
