---
layout: post
title: "Nonparametric location tests for one and two samples"
categories: [Nonparametric, ClassicalNonparametric]
rerCat: Nonparametric
tags: [Nonparametric, ClassicalNonparametric]
---

Nonparametric location tests for one and two samples
=========================

Install required packages
-------------------------

[`coin`](http://cran.r-project.org/package=coin)

```{r}
wants <- c("coin")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

One-sample
-------------------------

### Sign-test
    
```{r}
set.seed(1.234)
medH0 <- 30
DV    <- sample(0:100, 20, replace=TRUE)
DV    <- DV[DV != medH0]
N     <- length(DV)
(obs  <- sum(DV > medH0))
```

```{r}
(pGreater <- 1-pbinom(obs-1, N, 0.5))
(pTwoSided <- 2 * pGreater)
```

### Wilcoxon signed rank test

```{r}
IQ    <- c(99, 131, 118, 112, 128, 136, 120, 107, 134, 122)
medH0 <- 110
```

```{r}
wilcox.test(IQ, alternative="greater", mu=medH0, conf.int=TRUE)
```

Two independent samples
-------------------------

### Sign-test

```{r}
Nj  <- c(20, 30)
DVa <- rnorm(Nj[1], mean= 95, sd=15)
DVb <- rnorm(Nj[2], mean=100, sd=15)
wIndDf <- data.frame(DV=c(DVa, DVb),
                     IV=factor(rep(1:2, Nj), labels=LETTERS[1:2]))
```

Looks at the number of cases in each group which are below or above the median of the combined data.

```{r}
library(coin)
median_test(DV ~ IV, distribution="exact", data=wIndDf)
```

### Wilcoxon rank-sum test (\(=\) Mann-Whitney \(U\)-test)

```{r}
wilcox.test(DV ~ IV, alternative="less", conf.int=TRUE, data=wIndDf)
```

```{r}
library(coin)
wilcox_test(DV ~ IV, alternative="less", conf.int=TRUE,
            distribution="exact", data=wIndDf)
```

Two dependent samples
-------------------------

### Sign-test

```{r}
N      <- 20
DVpre  <- rnorm(N, mean= 95, sd=15)
DVpost <- rnorm(N, mean=100, sd=15)
wDepDf <- data.frame(id=factor(rep(1:N, times=2)),
                     DV=c(DVpre, DVpost),
                     IV=factor(rep(0:1, each=N), labels=c("pre", "post")))
```

```{r}
medH0  <- 0
DVdiff <- aggregate(DV ~ id, FUN=diff, data=wDepDf)
(obs   <- sum(DVdiff$DV < medH0))
```

```{r}
(pLess <- pbinom(obs, N, 0.5))
```

### Wilcoxon signed rank test

```{r}
wilcoxsign_test(DV ~ IV | id, alternative="greater",
                distribution="exact", data=wDepDf)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:coin))
try(detach(package:modeltools))
try(detach(package:survival))
try(detach(package:mvtnorm))
try(detach(package:splines))
try(detach(package:stats4))
```
