---
license: Creative Commons BY-SA
author: "Daniel Wollschlaeger"
title: "Add-on packages"
categories: [RBasics]
rerCat: R_Basics
tags: [Packages, CRAN]
---

Add-on packages
=========================

TODO
-------------------------

 - link to workspace for `search()`

Install required packages
-------------------------

[`coin`](https://cran.r-project.org/package=coin)

```{r}
wants <- c("coin")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Useful online resources
-------------------------

 * [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/web/packages/): These mirror servers are the primary hosts for contributed R add-on packages
 * [r-pkg.org](https://r-pkg.org/): Search and browse CRAN packages with a nicer user interface
 * [CRAN Task Views](https://cran.r-project.org/web/views/): An organized and maintained list of packages useful for a specific data analysis task (e.g., multivariate statistics or psychometric models)
 * [BioConductor](http://www.bioconductor.org/): A host for add-on packages especially useful for genomic data analysis
 * [rdrr.io](https://rdrr.io/): Search R related content - packages / help files

Install and update add-on packages
-------------------------

### Information about installed packages

```{r}
.libPaths()
find.package("coin")
```

```{r eval=FALSE}
installed.packages()
# not shown (very long output)
```

Show first 10 of all installed packages

```{r}
all_pkgs <- rownames(installed.packages())
head(all_pkgs, n=10)
```

```{r eval=FALSE}
library()
# not shown (opens separate window)
```

### Install and remove add-on packages

```{r eval=FALSE}
setRepositories("https://cloud.r-project.org/")
install.packages(c("coin", "car"))
install.packages("coin", repos="https://cran.at.r-project.org/")
update.packages()
# remove.packages("coin")
# not shown
```

See `install_github()` from package [`remotes`](https://cran.r-project.org/package=remotes) for installing from [GitHub](https://github.com/) repositories.

### Information provided by add-on packages

```{r eval=FALSE}
help(package="coin")
vignette()
vignette(package="coin")
vignette("coin_implementation")
# not shown (opens separate window)
```

Use add-on packages
-------------------------

### Load add-on package

`library()` throws an error if the package cannot be found, unless option `logical.return=TRUE` is set.

```{r}
library(coin)
```

Get a return value `TRUE` or `FALSE` that indicates whether package could be loaded

```{r}
library(doesNotExist, logical.return=TRUE)
```

### Know which packages are currently loaded

```{r}
sessionInfo()
search()
```

### Is one package masking functions from a different package?

If different packages provide functions with the same name, the function from the package loaded later *masks* the function from the package loaded earlier. Check if this happened:

```{r}
conflicts(detail=TRUE)
```

Explicitly state which package a function should be taken from.

```{r}
base::mean(c(1, 3, 4))
```

### Un-load a package

```{r eval=FALSE}
detach(package:coin, unload=TRUE)
```

Data sets from add-on packages
-------------------------

```{r eval=FALSE}
data(package="coin")
data(jobsatisfaction, package="coin")
# not shown (opens separate window)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:coin))
try(detach(package:survival))
```
