---
title: "Recode variables"
author: "Daniel Wollschlaeger"
license: Creative Commons BY-SA
categories: [RBasics]
rerCat: R_Basics
tags: [RBasics]
---

Recode variables
=========================

TODO
-------------------------

 - link to factors

Install required packages
-------------------------

[`car`](http://cran.r-project.org/package=car), [`DescTools`](http://cran.r-project.org/package=DescTools)

```{r}
wants <- c("dplyr", "forcats")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Recode numerical or character variables
-------------------------
    
### Using index vectors

```{r}
myColors <- c("red", "purple", "blue", "blue", "orange", "red", "orange")
farben   <- character(length(myColors))
farben[myColors == "red"]    <- "rot"
farben[myColors == "purple"] <- "violett"
farben[myColors == "blue"]   <- "blau"
farben[myColors == "orange"] <- "orange"
farben
```

```{r}
replace(c(1, 2, 3, 4, 5), list=c(2, 4), values=c(200, 400))
```

### Using `recode()` from package `dplyr`

```{r}
library(dplyr)
recode(myColors, red="rot", blue="blau", purple="violett")
```

```{r}
recode(myColors, red="basic", blue="basic", .default="complex")
```

### Using `ifelse()`

```{r}
orgVec <- c(5, 9, 11, 8, 9, 3, 1, 13, 9, 12, 5, 12, 6, 3, 17, 5, 8, 7)
cutoff <- 10
(reVec <- ifelse(orgVec <= cutoff, orgVec, cutoff))
```

```{r}
targetSet <- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K")
response  <- c("Z", "E", "O", "W", "H", "C", "I", "G", "A", "O", "B")
(respRec  <- ifelse(response %in% targetSet, response, "other"))
```

Cut continuous variables into categorical variables
-------------------------

### Free recoding of value ranges into categories

Two intervals

```{r}
set.seed(123)
IQ <- rnorm(20, mean=100, sd=15)
ifelse(IQ >= 100, "hi", "lo")
```

Multiple intervals

```{r}
library(dplyr)
case_when((IQ <= 100)              ~ 1,
          (IQ > 100) & (IQ <= 115) ~ 2,
          (IQ > 115)               ~ 3)
```

### Turn ordered value ranges into factor levels using `cut()`

```{r}
IQfac <- cut(IQ, breaks=c(0, 85, 115, Inf), labels=c("lo", "mid", "hi"))
head(IQfac)
```

```{r}
medSplit <- cut(IQ, breaks=c(-Inf, median(IQ), Inf))
summary(medSplit)
```

```{r}
IQdiscr <- cut(IQ, quantile(IQ), include.lowest=TRUE)
summary(IQdiscr)
```

Recode factors
-------------------------

### Change names of factor levels

```{r}
sex <- c(1, 0, 0, 1, 1, 1, 0, 0)
(sexFac <- factor(sex, levels=0:1, labels=c("f", "m")))
levels(sexFac) <- c("female", "male")
sexFac
```

Using package `forcats`

```{r}
library(forcats)
fct_recode(sexFac, "F"="female", "M"="male")
```

### Add, combine and remove factor levels

#### Add factor levels

```{r}
(status <- factor(c("hi", "lo", "hi")))
status[4] <- "mid"
status
levels(status) <- c(levels(status), "mid")
status[4] <- "mid"
status
```

Using package `forcats`

```{r}
fct_expand(status, "new_level")
```

#### Combine factor levels

```{r}
hiNotHi <- status
levels(hiNotHi) <- list(hi="hi", notHi=c("mid", "lo"))
hiNotHi
```

Using package `forcats`

```{r}
fct_collapse(status, notHi=c("mid", "lo"))
```

#### Remove factor levels

```{r}
status[1:2]
(newStatus <- droplevels(status[1:2]))
```

Using package `forcats`

```{r}
fct_drop(status[1:2], "mid")
```

### Reorder factor levels

#### Using `fct_relevel()` from package `forcats`

```{r}
(facGrp <- factor(rep(LETTERS[1:3], each=5)))
library(forcats)
fct_relevel(facGrp, "A", after=1)
fct_relevel(fac1, "A", after=Inf)
```

#### Reorder group levels according to group statistics

```{r}
vec <- rnorm(15, rep(c(10, 5, 15), each=5), 3)
tapply(vec, facGrp, FUN=mean)
reorder(facGrp, vec, FUN=mean)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:dplyr))
try(detach(package:forcats))
```
