---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Moderated and mediated linear regression"
categories: [Univariate, Regression]
rerCat: Univariate
tags: [Regression]
---

Moderated and mediated linear regression
=========================

TODO
-------------------------

 - link to regression, regressionDiag

Install required packages
-------------------------

[`mediation`](http://cran.r-project.org/package=mediation), [`multilevel`](http://cran.r-project.org/package=multilevel), [`rockchalk`](http://cran.r-project.org/package=rockchalk)

```{r}
wants <- c("mediation", "multilevel", "rockchalk")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```
    
Moderated regression
-------------------------

```{r}
set.seed(123)
N  <- 100
X1 <- rnorm(N, 175, 7)
X2 <- abs(rnorm(N, 60, 30))
M  <- rnorm(N,  30, 8)
Y  <- 0.5*X1 - 0.3*M - 0.4*X2 + 10 + rnorm(N, 0, 3)
```

```{r}
X1c    <- c(scale(X1, center=TRUE, scale=FALSE))
Mc     <- c(scale(M,  center=TRUE, scale=FALSE))
fitMod <- lm(Y ~ X1c + Mc + X1c:Mc)
coef(summary(fitMod))
```


```{r moderation}
library(rockchalk)
ps  <- plotSlopes(fitMod, plotx="X1c", modx="Mc", modxVals="std.dev")
(ts <- testSlopes(ps))
plot(ts)
```

Mediation analysis
-------------------------

### Simulate data

```{r}
N <- 100
X <- rnorm(N, 175, 7)
M <- 0.7*X + rnorm(N, 0, 5)
Y <- 0.4*M + rnorm(N, 0, 5)
dfMed <- data.frame(X, M, Y)
```

```{r}
fit <- lm(Y ~ X + M, data=dfMed)
summary(fit)
```

### Sobel test

```{r}
library(multilevel)
sobel(dfMed$X, dfMed$M, dfMed$Y)
```

### Using package `mediation`

Also useful for much more complicated situations.

#### Estimation via quasi-Bayesian approximation

```{r}
fitM <- lm(M ~ X,     data=dfMed)
fitY <- lm(Y ~ X + M, data=dfMed)

library(mediation)
fitMed <- mediate(fitM, fitY, sims=999, treat="X", mediator="M")
summary(fitMed)
```

```{r rerRegressionModMed01}
plot(fitMed)
```

#### Estimation via nonparametric bootstrap

```{r}
fitMedBoot <- mediate(fitM, fitY, boot=TRUE, sims=999, treat="X", mediator="M")
summary(fitMedBoot)
```

Useful packages
-------------------------

More complex structural equation models are supported by packages [`sem`](http://cran.r-project.org/package=sem), [`OpenMx`](http://openmx.psyc.virginia.edu/), and [`lavaan`](http://cran.r-project.org/package=lavaan). More packages can be found in CRAN task view [Psychometric Models](http://cran.r-project.org/web/views/Psychometrics.html).

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:rockchalk))
try(detach(package:mediation))
try(detach(package:Matrix))
try(detach(package:lpSolve))
try(detach(package:multilevel))
try(detach(package:MASS))
try(detach(package:nlme))
try(detach(package:sandwich))
try(detach(package:mvtnorm))
```
