---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Stratified bootstrapping"
categories: [Nonparametric, Resampling]
rerCat: Nonparametric
tags: [Bootstrapping]
---

Stratified bootstrapping
========================================================

TODO
-------------------------

 - link to resamplingBoot

Install required packages
-------------------------

[`boot`](https://cran.r-project.org/package=boot)

```{r}
wants <- c("boot")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Stratified sampling for two independent groups
-------------------------

### Confidence interval for \(\mu_{2} - \mu_{1}\)

```{r}
set.seed(123)
n1  <- 18
n2  <- 21
DVm <- rnorm(n1, 180, 10)
DVf <- rnorm(n2, 175, 6)
tDf <- data.frame(DV=c(DVm, DVf),
                  IV=factor(rep(c("m", "f"), c(n1, n2))))
```

Function to return difference between group means.

```{r}
getDM <- function(dat, idx) {
    Mfm <- aggregate(DV ~ IV, data=dat, subset=idx, FUN=mean)
    -diff(Mfm$DV)
}
```

Bootstrap with `strata` option for stratification.

```{r}
library(boot)
bsTind <- boot(tDf, statistic=getDM, strata=tDf$IV, R=999)
boot.ci(bsTind, conf=0.95, type=c("basic", "bca"))
```

Compare with parametric confidence interval

```{r}
tt <- t.test(DV ~ IV, alternative="two.sided", var.equal=TRUE, data=tDf)
tt$conf.int
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:boot))
```
