---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Data transformations"
categories: [RBasics]
rerCat: R_Basics
tags: [RBasics]
---

Data transformations
=========================

TODO
-------------------------

 - link to recode, dataFrames

 Install required packages
-------------------------

[`car`](https://cran.r-project.org/package=car)

```{r}
wants <- c("car")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Convert between data types
-------------------------

### Type hierarchy

Lower types can be uniquely converted to higher types.

```{r}
tfVec <- c(TRUE, FALSE, FALSE, TRUE)
as.numeric(tfVec)
as.complex(tfVec)
as.character(tfVec)
```

Higher types cannot be uniquely converted to lower types.

```{r warning=TRUE}
as.logical(c(-1, 0, 1, 2))
as.numeric(as.complex(c(3-2i, 3+2i, 0+1i, 0+0i)))
as.numeric(c("21", "3.141", "abc"))
```

Change order of vector elements
-------------------------

### Sort vectors

```{r}
vec <- c(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)
rev(vec)
vec <- c(10, 12, 1, 12, 7, 16, 6, 19, 10, 19)
sort(vec)
(idxDec <- order(vec, decreasing=TRUE))
vec[idxDec]
sort(c("D", "E", "10", "A", "F", "E", "D", "4", "E", "A"))
```

### Randomly permute vector elements

```{r}
set.seed(123)
myColors  <- c("red", "green", "blue", "yellow", "black")
(randCols <- sample(myColors, length(myColors), replace=FALSE))
```

```{r}
P   <- 3
Nj  <- c(4, 3, 5)
(IV <- rep(1:P, Nj))
(IVrand <- sample(IV, length(IV), replace=FALSE))
```

Randomly place elements in \(p\) groups of approximately equal size
-------------------------

```{r}
x <- c(18, 11, 15, 20, 19, 10, 14, 13, 10, 10)
N <- length(x)
P <- 3
(sample(1:N, N, replace=FALSE) %% P) + 1
```

Select random or systematic subsets of vector elements
-------------------------

### Random selection

```{r}
vec <- rep(c("red", "green", "blue"), 10)
sample(vec, 5, replace=FALSE)
```

```{r}
library(car)
some(vec, n=5)
```

### Select every 10th element

```{r}
selIdx1 <- seq(1, length(vec), by=10)
vec[selIdx1]
```

### Select approximately every 10th element

```{r}
selIdx2 <- rbinom(length(vec), size=1, prob=0.1) == 1
vec[selIdx2]
```

Transform old variables into new ones
-------------------------

### Element-wise arithmetic

```{r}
age <- c(18, 20, 30, 24, 23, 21)
age/10
(age/2) + 5
vec1 <- c(3, 4, 5, 6)
vec2 <- c(-2, 2, -2, 2)
vec1*vec2
vec3 <- c(10, 100, 1000, 10000)
(vec1 + vec2) / vec3
```

### Recycling rule

```{r warning=TRUE}
vec1 <- c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24)
vec2 <- c(2, 4, 6, 8, 10)
c(length(age), length(vec1), length(vec2))
vec1*age
vec2*age
```

### Standardize variables

```{r}
(zAge <- (age - mean(age)) / sd(age))
(zAge <- scale(age))
as.vector(zAge)
```

### Move and scale variable

```{r}
newSd   <- 15
newMean <- 100
(newAge <- (as.vector(zAge)*newSd) + newMean)
mean(newAge)
sd(newAge)
```

### Rank transformation

```{r}
rank(c(3, 1, 2, 3))
```

### Transform old variables into new ones

```{r}
height <- c(1.78, 1.91, 1.89, 1.83, 1.64)
weight <- c(65, 89, 91, 75, 73)
(bmi   <- weight / (height^2))
```

```{r}
quest1  <- c(FALSE, FALSE, FALSE, TRUE,  FALSE, TRUE, FALSE, TRUE)
quest2  <- c(TRUE,  FALSE, FALSE, FALSE, TRUE,  TRUE, TRUE,  FALSE)
quest3  <- c(TRUE,  TRUE,  TRUE,  TRUE,  FALSE, TRUE, FALSE, FALSE)
(sumVar <- quest1 + quest2 + quest3)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:car))
try(detach(package:carData))
```
