---
license: Creative Commons BY-SA
author: Daniel Wollschlaeger
title: "Variance homogeneity in two or more groups"
categories: [Univariate]
rerCat: Univariate
tags: [ANOVA, tTests]
---

Variance homogeneity in two or more groups
=========================

TODO
-------------------------

 - link to variance

Install required packages
-------------------------

[`car`](https://cran.r-project.org/package=car), [`coin`](https://cran.r-project.org/package=coin), [`beeswarm`](https://cran.r-project.org/package=beeswarm)

```{r}
wants <- c("car", "coin", "beeswarm")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

Compare two groups
-------------------------

### Boxplot with added beeswarm plot

```{r}
set.seed(123)
P     <- 2
Nj    <- c(50, 40)
DV1   <- rnorm(Nj[1], mean=100, sd=15)
DV2   <- rnorm(Nj[2], mean=100, sd=13)
varDf <- data.frame(DV=c(DV1, DV2),
                    IV=factor(rep(1:P, Nj)))
```

```{r rerVarHom01}
library(beeswarm)
boxplot(DV ~ IV, data=varDf)
beeswarm(DV ~ IV, data=varDf, add=TRUE, pch=16, col="#00000077")
```

### \(F\)-test for variance ratio in two groups

```{r results='hide'}
var.test(DV1, DV2)
```

```{r}
var.test(DV ~ IV, data=varDf)
```

### Mood-test for two groups (nonparametric)

```{r}
mood.test(DV ~ IV, alternative="greater", data=varDf)
```

### Ansari-Bradley-test for two groups (nonparametric)

```{r}
ansari.test(DV ~ IV, alternative="greater", exact=FALSE, data=varDf)
```

```{r}
library(coin)
ansari_test(DV ~ IV, alternative="greater", distribution="exact", data=varDf)
```

Compare more than two groups
-------------------------

### Boxplot with added beeswarm plot

```{r}
Nj    <- c(22, 18, 20)
N     <- sum(Nj)
P     <- length(Nj)
levDf <- data.frame(DV=sample(0:100, N, replace=TRUE),
                    IV=factor(rep(1:P, Nj)))
```

```{r rerVarHom02}
library(beeswarm)
boxplot(DV ~ IV, data=levDf)
beeswarm(DV ~ IV, data=levDf, add=TRUE, pch=16, col="#00000077")
```

### Levene-test

```{r}
library(car)
leveneTest(DV ~ IV, center=median, data=levDf)
leveneTest(DV ~ IV, center=mean, data=levDf)
```

### Fligner-Killeen-test

```{r}
fligner.test(DV ~ IV, data=levDf)
```

```{r}
library(coin)
fligner_test(DV ~ IV, distribution=approximate(nresample=9999), data=levDf)
```

Detach (automatically) loaded packages (if possible)
-------------------------

```{r}
try(detach(package:car))
try(detach(package:carData))
try(detach(package:coin))
try(detach(package:survival))
try(detach(package:beeswarm))
```
